### ISSUE TITLE
packet class refinery

### ISSUE THREAD

**Issue by Reptudn** [FreddyMSchubert/42_webserv#16]
make the packet class secure with _is_empty if some member vars are empty and so on

**Comment by FreddyMSchubert** [comment]
Im repurposing this issue. Packet class only handles packet building, parsing is done in request, answer gen is done is response. both use packets packet builder. thats better oop. also, what he said.

**Comment by Reptudn** [comment]
> Im repurposing this issue. Packet class only handles packet building, parsing is done in request, answer gen is done is response. both use packets packet builder. thats better oop. also, what he said.

i will only touch the Get.cpp file in the methods directory in #20 so it would be nice if you do what you said and keep the functionality of the get file working even after merge

**Comment by FreddyMSchubert** [comment]
i completely rewrote that file before reading this, youre welcome :)
