### ISSUE TITLE
delete requests

### ISSUE THREAD

**Issue by Reptudn** [FreddyMSchubert/42_webserv#19]
- is the path a file or directory?
    - FILE: delete file (don't know if we should do some access stuff here already)
    - DIRECTORY: uri ends with / ?
        - NO: return 409 error
        - YES: We have write access?
            - NO:  return 403 error
            - YES: trying to delete dir ->  return 500 on error and 204 on success

**Comment by FreddyMSchubert** [comment]
https://github.com/FreddyMSchubert/42_webserv/issues/48
