### ISSUE TITLE
basic socket

### ISSUE THREAD

**Issue by Reptudn** [FreddyMSchubert/42_webserv#2]
run a simple socket that nus on given port 

https://ncona.com/2019/04/building-a-simple-server-with-cpp/

**Comment by FreddyMSchubert** [comment]
maybe this is helpful
https://chatgpt.com/share/6704e9d3-7cd4-800d-b242-3259ce8e994c

**Comment by Reptudn** [comment]
my bad i worked on wrong branch its already on main
