### ISSUE TITLE
get request

### ISSUE THREAD

**Issue by Reptudn** [FreddyMSchubert/42_webserv#20]
## directory listing policies
- without directory listing: users are only allowed to access that exact folder and no sub folders
- with directory listing: users are allowed to access that folder and all sub directories unless specified otherwise when a location of the subdirectory is also a location inside the config

## directory listing style
- better style for dir listing

**Comment by FreddyMSchubert** [comment]
life is pain, existence is suffering, reptudn exists.

permission are hard and they do not work.
