### ISSUE TITLE
fix chunked transfer

### ISSUE THREAD

**Issue by FreddyMSchubert** [FreddyMSchubert/42_webserv#24]
its very broken not working at all

**Comment by FreddyMSchubert** [comment]
Well, this needs a lot more attention.

We can't just read out all of the data and then parse it separately, we need to actually collect the data live as we receive it. Otherwise, if someone was to send an infinite data stream, our server would be blocked forever, which is not allowed as per the subject.

I've deleted the previous branch, this needs a larger rework.

Lemme sketch out how I think this might work before getting started, anything might change:

So, lets make
- a ConnectionManager that keeps track of all connections a server has (would be a member of server class)
	- contains connection struct with a struct pollfd -> fd + other connection data & string to accumulate data & ref to Socket that handles it
	- one per server. this is where poll gets called, and it updates the connection data
	- Socket then gets called not generally for all clients but by the ConnectionManage with a specific client in mind.

1. Server calls on ConnectionManager to update
2. ConnectionManager gets up-to-date infos using poll
3. ConnectionManager goes through connections.
	- If they were closed from the client-side, call closing function.
	- If they are still open, call its Socket to read new data & append to buffer string
	- If any buffer string exceeds it's allowed size, send a 413 and close connection
4. If IsClosed returns true, parse it & respond & close

IsClosed function
- Basic parsing to verify whether a full packet was received (needs to handle both normal & chanked transfer encoding)
- returns bool

Closing function
- Check with IsClosed function whether packet is done
- If it was, form a respond and send it using the socket
- If it wasn't, clean up the connection.

Given that the goal of this project is merely to serve a fully static website, sending in chunk transfer encoding is not something I deem to be strictly necessary at the moment. I'd just... not do that.

**Comment by Reptudn** [comment]
sounds good lets do that
i found a good source on how other people did it [here](https://rickroll.it/rickroll.mp4)

**Comment by NoelSabia** [comment]
can we close this? #41 is now the main issue to work on.

**Comment by FreddyMSchubert** [comment]
this man saw the issue with all the context decided to open an empty one, create the branch there, and then advocate to close the initial issue. can we get him a prize?

issues fixed though closing this now.
