### ISSUE TITLE
cookies

### ISSUE THREAD

**Issue by NoelSabia** [FreddyMSchubert/42_webserv#51]
- [ ] Cookie header parsing
- [ ] Session ID generation
- [ ] Basic in-memory session storage
- [ ] Proper CGI environment variable setting is sufficient for the bonus part

**Comment by NoelSabia** [comment]
- [ ] Cookie header parsing
- [ ] Session ID generation
- [ ] Basic in-memory session storage
- [ ] Proper CGI environment variable setting is sufficient for the bonus part

**Comment by FreddyMSchubert** [comment]
is this really necessary? handled entirely by cgi afaik. just gotta pass the data to the cgi scripts properly, should be fine.
closing this for now.
